package com.mycompany.Forms;

import com.mycompany.Clases.Libro;
import com.mycompany.Clases.Usuario;
import java.awt.HeadlessException;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import org.json.JSONArray;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.json.JSONObject;

public class ConsultaLibros extends javax.swing.JFrame {
        
    private Libro libro;
    private java.util.List<Libro> librosActivos;
    
    public ConsultaLibros() {
        initComponents();
        setLocationRelativeTo(null);
        pintar_tabla();
        
        this.setDefaultCloseOperation(Login.DISPOSE_ON_CLOSE); // Para evitar que al dar en la equis, se cierre el form principal.
    }
        
     private void pintar_tabla(){
                
        String encabezado [] = {"Título", "Autor", "Precio de Compra", "Precio de Venta", "Género", "Cantidad"};
        
        // Filtrando libros activos
        librosActivos = new java.util.ArrayList<>();
        for (Libro l : Proyecto_Final_Log_In.libros) {
            if (l.activo) {
                librosActivos.add(l);
            }
        }
        
        
        // Crear modelo con columnas, pero sin filas
        DefaultTableModel t = new DefaultTableModel(encabezado, 0);
        jTable1.setModel(t);
        
        TableModel tabla = jTable1.getModel();
        
        for (Libro l : librosActivos) {
            Object[] fila = {l.titulo, l.autor, l.precio_compra, l.precio_venta, l.genero, l.cantidad};
            t.addRow(fila);
        }
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        Guardar = new javax.swing.JButton();
        Borrar = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        CargaMasiva = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consulta de Libros");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setName(""); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        Borrar.setText("Borrar");
        Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarActionPerformed(evt);
            }
        });

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        jLabel1.setText("Autor:");

        jLabel2.setText("Titulo:");

        jLabel3.setText("Precio Compra:");

        jLabel4.setText("Precio Venta:");

        jLabel5.setText("Género:");

        jLabel6.setText("Cantidad");

        CargaMasiva.setText("Carga Masiva");
        CargaMasiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargaMasivaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(Borrar)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(Modificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CargaMasiva)
                                .addGap(41, 41, 41)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Guardar)
                                .addGap(9, 9, 9)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Modificar)
                    .addComponent(jButton1)
                    .addComponent(Borrar)
                    .addComponent(CargaMasiva))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Guardar)
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 17, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed

        if (libro != null) {
            libro.titulo = jTextField1.getText();
            libro.autor = jTextField2.getText();
            libro.precio_compra = Double.parseDouble(jTextField3.getText());
            libro.precio_venta = Double.parseDouble(jTextField4.getText());
            libro.genero = jTextField5.getText();
            libro.cantidad= Integer.parseInt(jTextField6.getText());
           
            pintar_tabla();

            JOptionPane.showMessageDialog(this, "Libro modificado exitosamente.");
        }
    }//GEN-LAST:event_GuardarActionPerformed

    private void BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarActionPerformed

        int eliminar = jTable1.getSelectedRow();

        if(eliminar >= 0){
            if(JOptionPane.showConfirmDialog(this, "¿Estás seguro que deseas eliminar el libro seleccionado?") == 0){

                libro = librosActivos.get(eliminar);
                //Proyecto_Final_Log_In.libros.remove(eliminar);  Ya no se elmina de la lista de objetos de tipo Libro.
                libro.activo = false;
                pintar_tabla();
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Selecciona un libro válido para eliminar.");
        }
    }//GEN-LAST:event_BorrarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed

        if(jTable1.getSelectedRow() >= 0 ){
            libro = librosActivos.get(jTable1.getSelectedRow());
            jTextField1.setText(libro.titulo);
            jTextField2.setText(libro.autor);
            jTextField3.setText(String.valueOf(libro.precio_compra));
            jTextField4.setText(String.valueOf(libro.precio_venta));
            jTextField5.setText(libro.genero);
            jTextField6.setText(String.valueOf(libro.cantidad));
            
        }
        else{
            JOptionPane.showMessageDialog(this, "Selecciona un libro válido para modificar.");
        }
    }//GEN-LAST:event_ModificarActionPerformed
    
    private String obtenerRuta(){
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos Json (*.json)", "json");
        
        fileChooser.setFileFilter(filtro);
        
        fileChooser.showOpenDialog(null);
        File archivo = fileChooser.getSelectedFile();
        
       int respuesta = JOptionPane.showConfirmDialog(null, "¿Desea  cargar el archivo: \"" + archivo.getAbsolutePath() + "\"?", "Confirmación", JOptionPane.INFORMATION_MESSAGE);
        
       if (respuesta == JOptionPane.YES_OPTION) {
            return archivo.getAbsolutePath();
        } else {
            JOptionPane.showMessageDialog(
                null,
                "Selección cancelada.",
                "Cancelado",
                JOptionPane.WARNING_MESSAGE
            );
        } 
       
        return null;
    }
    
    private void leer(String ruta){
        
        try {
            // Leyendo todo el contenido del archivo como String
            String contenido = new String(Files.readAllBytes(Paths.get(ruta)));
            
            // Creando el objeto JSONObject a partir del String
            JSONObject json = new JSONObject(contenido);
            
            // Obtener datos del JSON
            JSONArray usuarios = json.getJSONArray("Usuarios");

            for (int i = 0; i < usuarios.length(); i++) {
                JSONObject usuario = usuarios.getJSONObject(i);
                String titulo = usuario.getString("titulo");
                int autor = usuario.getInt("autor");
                int precio = usuario.getInt("precio");
                int cantidad = usuario.getInt("cantidad");
                int genero = usuario.getInt("genero");
                System.out.println("Título: " + titulo + ", Autor: " + autor + ", Precio: " + precio + ", Cantidad: " + cantidad + ", Genero: " + genero);
            }
            
            for(int j = 0; j < nodos.getLength(); j++){
                Node nodo = nodos.item(j);
                
                if(nodo.getNodeType() == Node.ELEMENT_NODE){
                    
                    try{
                        Element elemento = (Element) nodo;
                        String pass = elemento.getElementsByTagName("contraseña").item(0).getTextContent();

                        boolean validLength = true;
                        boolean validNumber = false;
                        boolean validLower = false;
                        boolean validCapital = false;
        
                        if(pass.length() < 6){
                            validLength = false;
                            continue;
                        }
        
                        
                        for(int i = 0; i < pass.length(); i++){
                            int ascii = (int) pass.charAt(i);
            
                            if(ascii >= 48 && ascii <= 57){ // Rango ASCII de los dígitos.
                                validNumber = true;
                            }
                        }
                        if(!validNumber){
                            continue;
                        }
        
                        
                        for(int i = 0; i < pass.length(); i++){ // Rango ASCII de las mayusculas.
                            int ascii = (int) pass.charAt(i);
            
                            if(ascii >= 65 && ascii <= 90){
                                validCapital = true;
                            }
                        }
                        if(!validCapital){
                            continue;
                        }
        
                        
                        for(int i = 0; i < pass.length(); i++){
                            int ascii = (int) pass.charAt(i);
            
                            if(ascii >= 97 && ascii <= 122){ // Rango ASCII de las minusculas.
                                validLower = true;
                            }
                        }
                        if(!validLower){
                            continue;
                        }
                
                        
                        if((validLength == true)&&(validNumber == true)&&(validCapital == true)&&(validLower == true)){
                            Usuario u = new Usuario();
                            u.nombre = elemento.getElementsByTagName("nombre").item(0).getTextContent();
                            u.usuario = elemento.getElementsByTagName("user").item(0).getTextContent();
                            u.password = pass;
                            String Rol = elemento.getElementsByTagName("rol").item(0).getTextContent();
                            
                            if(Rol.equalsIgnoreCase("Administrador")){
                                u.rol = "Administrador";
                            }else if(Rol.equalsIgnoreCase("Vendedor")){
                                u.rol = "Vendedor";
                            }else{
                                continue;
                            }
                            u.activo = true;
                            
                            Proyecto_Final_Log_In.usuarios.add(u);
                            
                        }
                    }
                    catch(HeadlessException e){
                        JOptionPane.showMessageDialog(this, "Error: " + e);
                    }
                }
            }
            
            JOptionPane.showMessageDialog(this, "Carga Masiva de Usuarios exitosa.");
            
        } catch (Exception ex) {
            Logger.getLogger(ConsultaUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void CargaMasivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargaMasivaActionPerformed
        String ruta = obtenerRuta();
        leer(ruta);
        pintar_tabla();
    }//GEN-LAST:event_CargaMasivaActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Borrar;
    private javax.swing.JButton CargaMasiva;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton Modificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
