package com.mycompany.Forms;

import com.mycompany.Clases.Libro_Vendido;
import com.mycompany.Clases.Venta;
import java.awt.Dimension;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class DetalleVenta extends javax.swing.JFrame {
    
    private Venta venta;
    
    public DetalleVenta(Venta ventaSeleccionada) {
        System.out.println(ventaSeleccionada);
        venta = ventaSeleccionada;
        initComponents();
        setLocationRelativeTo(null);
        this.setDefaultCloseOperation(Login.DISPOSE_ON_CLOSE); 
        
        getContentPane().setBackground(new java.awt.Color(0, 0, 0));
        customizeTableHeader();
        
        pintar_tabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consulta de Ventas");
        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Detalle de la Venta");

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Regresar");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionForeground(new java.awt.Color(15, 42, 61));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(jLabel1)
                        .addGap(0, 382, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void pintar_tabla(){
                
            String encabezado [] = {"Libro", "Cantidad", "Subtotal", "Subtotal Sin IVA"};
            
            DefaultTableModel t = new DefaultTableModel(encabezado, 0);
            jTable1.setModel(t);

            TableModel tabla = jTable1.getModel();

            if(Proyecto_Final_Log_In.itemVentaSeleccionada >= 0){
                System.out.println(ConsultaVentas.ventaSelected.getLibrosVendidos());
                for (Libro_Vendido v : venta.getLibrosVendidos()) {
                    Object[] fila = {v.getLibro(), v.getCantidad(), v.getSubtotal(), Math.round((v.getSubtotal()/1.12)*100.0)/100.0};
                    t.addRow(fila);
                }    
            }
            else{
                JOptionPane.showMessageDialog(this, "Selecciona una venta válida.");
            }
        }
    
    private void customizeTableHeader() {
        // 1. Obtener el header de la tabla
        javax.swing.table.JTableHeader header = jTable1.getTableHeader();  // Nombre de tu tabla

        // 2. Configurar estilo
        Font headerFont = new Font("Liberation Sans", Font.BOLD, 16); // Cambia el tamaño aquí (14, 16, etc.)
        header.setPreferredSize(new Dimension(header.getWidth(), 35));
        header.setFont(headerFont);
        header.setBackground(new java.awt.Color(0, 0, 0));  // Color de fondo (RGB)
        header.setForeground(java.awt.Color.WHITE);             // Color del texto
        
        jScrollPane1.getViewport().setBackground(new java.awt.Color(0, 0, 0));
        
        // 3. (Opcional) Forzar repintado
        header.repaint();
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
